config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  controller :pages, action: :show do
    root page: 'home'
    %w(composer_nights music_tech contact).each do |page|
      path = page.gsub('_', '')
      name = page.gsub('/', '_')
      get path, as: name, page: name
    end
  end

  scope 'composernights/signup', controller: :signups do
    get   '/', action: :new, as: :signup
    post  '/', action: :create
    post  :send_edit_link, as: :signup_edit_link
    get   '/:token', action: :edit, as: :edit_signup
    patch '/:token', action: :update
  end

end

app/models/signup.rb
class Signup < ActiveRecord::Base
  belongs_to :presenter, class_name: "Person"
  belongs_to :composer_night, touch: true
  has_many :preferences, class_name: "SignupPreference", dependent: :destroy, autosave: true

  accepts_nested_attributes_for :presenter, :preferences

  validates :presenter, presence: true

  attr_accessor :read_guidelines

  scope :active,      -> { where(active: true) }
  scope :upcoming,    -> { active.where(composer_night: ComposerNight.upcoming) }
  scope :unscheduled, -> { active.where(composer_night: nil) }
  scope :in_queue,    -> { active.where(composer_night: ComposerNight.upcoming + [nil]) }

  before_save :populate_access_token

  after_create :subscribe_presenter_to_mailing_list

  def scheduled?
    composer_night_id?
  end

  def unscheduled?
    !scheduled?
  end

  def upcoming?
    composer_night.upcoming?
  end

  def past?
    composer_night.past?
  end

  def preference_for(composer_night)
    preferences.find_or_create_by!(composer_night: composer_night)
  end

  def preferences_for_upcoming
    @preferences_for_upcoming ||= ComposerNight.upcoming.reject(&:full?).map do |event|
      preference_for(event)
    end
  end

  def instance_variable_default(var)
    result = instance_variable_get(var)
    unless result
      result = yield
      instance_variable_set(var, result)
    end
    result
  end

  def required_info
    @signup.required_info ||= {
      presenter_name:  presenter.name,
      presenter_phone: presenter.phone,
      title:           title,
      performers:      performers,
      approx_length:   approx_length,
      special_needs:   special_needs
    }
  end

  def optional_info
    @signup.optional_info = {
      description:         description,
      presenter_url:       presenter.url,
      presenter_pronouns:  presenter.pronouns,
      presenter_bio:       presenter.bio
    }
  end

  def required_info_missing
    @signup.required_info_missing ||= required_info.select { |k,v| v.blank? }
  end

  def optional_info_missing
    @signup.optional_info_missing ||= optional_info.select { |k,v| v.blank? }
  end

  def info_provided
    @signup.info_provided ||= required_info.merge(optional_info).reject { |k,v| v.blank? }
  end

  def subscribe_presenter_to_mailing_list
    Delayed::Job.enqueue SubscribeToMailingList.new(presenter)
  end

private

  def populate_access_token
    self.access_token ||= SecureRandom.urlsafe_base64(18)
  end
end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController

  before_action :find_signup_by_token, only: [:edit, :update]
  around_action :wrap_in_transaction

  invisible_captcha only: [:create, :update],
    honeypot: :last_name,
    on_spam: :spam_filtered,
    on_timestamp_spam: :spam_filtered

  def new
    @signup = Signup.new
    @signup.presenter = Person.new
    render 'new'
  end

  def create
    presenter = Person.find_or_initialize_by(email: (presenter_params[:email] || '').downcase)
    existing = presenter.signups.in_queue.first
    if existing
      render 'already_in_queue'
      return
    end

    # Use existing name etc. if present; don't overwrite
    presenter.assign_attributes(
      presenter_params.reject { |k,v| v.blank? })

    @signup = signup = Signup.new(signup_params)
    signup.presenter = presenter

    changed_attrs = []
    %w(name phone).map do |attr|
      old_val = @signup.presenter.send("#{attr}_was")
      if @signup.presenter.send("#{attr}_changed?") && !old_val.blank?
        changed_attrs << [attr, old_val]
      end
    end

    if presenter.save && signup.save
      AdminNotifications.delay.signup(signup, true, Hash[changed_attrs])
      SignupsMailer.delay.touch_base(signup)
      flash[:success] = "Composer Night signup created"
      redirect_to edit_signup_path(token: signup.access_token, new: 1)
    else
      flash[:error] = "Unable to create Composer Night signup. Please correct the errors below."
      render :new
    end
  end

  def send_edit_link
    presenter = Person.find_by!(email: params[:email])
    signup = presenter.signups.in_queue.first

    SignupsMailer.delay.touch_base(signup)
    render :edit_link_sent
  end

  def edit
    if @signup.unscheduled?
      render 'choose_date'
    elsif @signup.upcoming?
      render 'program_info'
    else
      render 'performance_past'
    end
  end

  def update
    success =
      @signup.update(signup_params) &&
      @signup.presenter.update(presenter_params)
    
    if success
      flash[:success] = "Signup information updated"
      AdminNotifications.delay.signup(@signup, false)
      if @signup.unscheduled? && signup_prefs.any? { |p| p.status == 'unknown' }
        flash[:warning] = "Please don’t forget to provide your availability for the other dates below."
      end
      @signup_updated = true
    else
      flash[:error] = "Unable to update information. Please correct the problems below."
    end

    edit
  end

private

  def find_signup_by_token
    @signup = Signup.find_by!(access_token: params[:token])
  end

  def signup_params
    @signup_params ||=
      params.require(:signup).permit(
        :comments, :guidelines, :title, :performers, :approx_length, :description, :special_needs,
        preferences_attributes: [:id, :status])
  end

  def presenter_params
    @presenter_params ||= if params[:signup][:presenter_attributes]
      params[:signup].require(:presenter_attributes).permit(:email, :name, :pronouns, :phone, :url, :bio)
    else
      {}
    end
  end
  helper_method :presenter_params

  def signup_prefs
    @signup_prefs ||= @signup.preferences_for_upcoming
  end
  helper_method :signup_prefs

  def wrap_in_transaction(&block)
    Signup.transaction(&block)
  end

  def spam_filtered
    # AdminNotifications.delay.spam_filtered(params)
    flash[:info] = "The system thinks you are a bot. If you are a human, please check the directions on each field carefully."
    return redirect_to signup_path
  end

end

app/helpers/signups_helper.rb
module SignupsHelper
  def event_time(format)
    @signup.composer_night.start_time.strftime(format)
  end

  def semantic_form_for_signup(&block)
    semantic_form_for @signup, url: edit_signup_path(token: @signup.access_token), class: 'signup', &block
  end
end

app/views/signups/already_in_queue.html.haml
- content_for :title do
  Composer Nights – Your performance

.content
  %h2 Already in line
  %p
    #{random_greeting}, #{presenter_params[:email]}.
  %p
    You’re <b>already in line</b> to perform!
  %p
    Would you like to see — or change — the details? If so, press the big ol’ button:
  .mongo= link_to 'Send Editing Link', signup_edit_link_path(email: presenter_params[:email]), method: :post
  %p
    …and we’ll send you an email with a secure link to edit your info.

app/views/signups/choose_date.html.haml
- content_for :title do
  Composer Nights – Date selection

.content
  - if params[:new]
    %h2 Hooray!
    %p
      %b You’re now in the Composer Night queue!

    - unless @signup.presenter.mailing_list_subscription_offered
      %p
        If you’re not already on our mailing list, you will receive a Confirm Subscription” email. <b>Please click the confirmation link</b> in that email, or you won’t get announcements about when New Ruckus events are happening.
      %p
        (We <b>will not</b> share your contact information outside The New Ruckus.)
  
  - else
    %p
      #{random_greeting}, <b>#{@signup.presenter.name}</b>.
      You’re in line for a Composer Night!

  - if signup_prefs.any?
    = semantic_form_for_signup do |f|

      %h2 Date Choices

      %p
        When would you like to share your music?
      %p
        You don’t have to choose a date right away. We’ll hold your place in line as long as you want.
      %p
        However, if there are dates below you’re pretty sure you won’t want, please mark them “no” now so that we can offer them to other people!

      .date-preferences
        = f.semantic_fields_for :preferences, signup_prefs do |pref|
          .date-preference
            .date= pref.object.composer_night.start_time.strftime('<b>%b</b> %-d (%a)<br>%l:%M<span class="ampm">%P</span>').html_safe
            
            .statuses<>
              - SignupPreference::VISIBLE_STATUSES.each do |status|
                = pref.label "status_#{status}", class: "status #{status}" do
                  = pref.radio_button :status, status
                  = status
            
            .status-messages
              .status-message.yes   I’ll take it <b>if</b> it’s available! Let me know.
              .status-message.maybe Give me some time to figure out if this date works.
              .status-message.no    Go ahead and offer this date to the others who are after me in line.
              - if @signup_updated
                .status-message.unknown
                  .inline-error ← What about this date?
  
      %p
        Please note that saying “yes” <b>does not guarantee</b> you a spot, because there may be other people ahead of you in line.
      %p
        If a date is yours, we will send you confirmation.

      = f.input :comments, hint: 'Any special instructions? Questions or concerns?'

      = f.submit 'Save Changes'

  - else
    %p
      Alas, there are no Composer Nights with open slots right now. We’ll get in touch with you when we announce new dates!

app/views/signups/edit_link_sent.html.haml
- content_for :title do
  Composer Nights – Edit link sent

.content
  %h2 Link sent
  %p
    Look for it in your email in a minute or two.

app/views/signups/new.html.haml
- content_for :title do
  Composer Nights – Sign Up


= hero do
  %h1.title Composer Nights
  .subtitle
    %b Sign up
    to share your music

.content
  %p
    Want to share your music? We’d love to hear it at a
    <a href="/composernights">New Ruckus Composer Night</a>!

  %h2 Guidelines
  %ul
    %li
      %b It must be original music.
      You must be the composer / improviser / songwriter / sound artist / inventor of the music you’re signing up to present. You can bring others to perform your work, or you can perform it yourself — but either way, we want the music’s creator there as the guest of honor at
      <a href="http://www.studiozstpaul.com">Studio Z</a>
      in St. Paul, MN!
    %li
      %b It must fit the time and space constraints.
      No more than 15 minutes of music, please. (Shorter performances are just fine. If it’s very short, we might want to hear it twice!) Studio Z is not a concert hall or a stadium, so please make sure what you’re bringing will work in the space.
    %li
      %b You must provide your own performers, and provide any instruments not available at Studio Z.
      If you have special needs, or aren't sure which instruments are available for use at Composer Nights, please ask.
    %li
      %b
        We prefer live performances when possible, but recordings are fine
        %i if
        recording is your medium.
      The key here is that we want to hear the piece performed in the medium it was intended to be performed in.
    %li
      %b It's first come, first served.
      When you are at the front of the queue, you get first dibs on the available dates. You can only hold one place in line at a time, but you can get in line again immediately after you’ve had your turn.
  %ul
  %p
    Want to know more? Please read
    <a href="/composernights">about Composer Nights</a>.
    Questions?
    <a href="/contact">Please ask</a>.

  %h2 Sign-Up Form

  %p
    You don’t have to choose a date right away. You don’t even need to have a piece ready. Just let us know you’re interested, and we’ll be in touch!

  = semantic_form_for @signup, url: signup_path, html: { id: 'sign_up_form' } do |f|
    = f.inputs class: 'featured' do
      = f.fields_for :presenter do |p|
        = p.input :name, required: false, as: :string
        = invisible_captcha :last_name
        = p.input :email, required: false, as: :email, hint: 'Double check it!'
        = p.input :pronouns, required: false, as: :string, hint: 'What pronoun(s) should we use for you in our promotion materials? e.g. “she,” “he,” “they”'
      = f.input :comments, required: false, label: 'Comments or questions', as: :text
      = f.fields_for :presenter do |p|
        = p.input :phone, required: false, as: :phone, label: 'Phone', hint: t('signup.attrs.presenter_phone_hint').html_safe
      = f.input :read_guidelines, as: :boolean, label: 'I have read the guidelines above.'
      = f.action :submit, label: 'Sign me up!'

app/views/signups/performance_past.html.haml
- content_for :title do
  Composer Nights – Your performance

.content
  %p
    #{random_greeting}, #{@signup.presenter.name}.
    Thanks for sharing your music at Composer Night!
  %p
    %b Good for another round?
    Now that your performance is done, you can get right back in line!

  .mongo= link_to 'Sign Up', signup_path

app/views/signups/program_info.html.haml
- content_for :title do
  Composer Nights – Program info for your performance

.content
  %p
    #{random_greeting}, #{@signup.presenter.name}!
    You’re scheduled for the Composer Night on
    <b>#{event_time '%A, %B %-d'}</b>.
  %p
    The performance starts at
    <b>#{event_time '%l:%M'}<span class="ampm">#{event_time '%P'}</span></b>.
    You should be there at least 15 minutes early — or more like 30 if you have complex setup needs.
  %p
    If you’re driving, please leave a little extra time for parking. It can be a bear.

  = semantic_form_for_signup do |f|

    %h2 About you

    %p
      Share as much as you have right now. You can always add and update it later.

    = f.inputs do
      = f.fields_for :presenter do |p|
        = p.input :name, as: :string, hint: 'As you would like it to appear on the program and in publicity materials'
        = p.input :url, as: :string, label: 'URL of your web site', required: false, placeholder: 'http://'
        = p.input :pronouns, as: :string, hint: 'What pronoun(s) should we use for you in our promotion materials? e.g. “she,” “he,” “they”'
        = p.input :bio, hint: 'Just a few sentences for our publicity materials'
        = p.input :phone, required: false, as: :phone, label: 'Phone', hint: t('signup.attrs.presenter_phone_hint').html_safe

    %h2 About your performance

    = f.inputs do
      = f.input :title, label: 'Title of your piece(s)'
      = f.input :performers, label: 'Performers and instruments'
      = f.input :approx_length, label: 'Approximate length'
      = f.input :description, label: 'Description of the piece', hint: 'Just a sentence or two for our publicity materials'
      = f.input :special_needs, hint: 'Piano? Sound system? Projector? Something else?'
      = f.input :comments, hint: 'Anything else we should know?'

    = f.submit 'Save Changes'